---

### /etc/docker/daemon.json

- name: Create /etc/docker directory
  file:
    path: /etc/docker/
    state: directory
  register: create_etc_docker_directory

- name: Config custom /etc/docker/daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
    backup: yes
  register: config_custom_docker_daemon
  when:
    - create_etc_docker_directory
    - docker_custom_daemon != ""

### ~/.docker/config.json

- name: Create ~/.docker directory
  file:
    path: "{{ ansible_env.HOME }}/.docker"
    state: directory
  register: create_user_docker_directory

- name: Config custom ~/.docker/config.json
  template:
    src: config.json.j2
    dest: "{{ ansible_env.HOME }}/.docker/config.json"
    mode: 0644
    backup: yes
  when:
    - create_user_docker_directory
    - docker_custom_config != ""
